import { useState, type FormEvent } from "react";

import type { Invitation, ProjectSummary } from "@/api/types";
import { Button } from "@/components/ui/Button";
import { ConfirmDialog } from "@/components/ui/ConfirmDialog";
import { Dialog, DialogBody, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/Dialog";
import { EmptyState } from "@/components/ui/States";
import { StatusChip } from "@/components/ui/StatusChip";
import { useToast } from "@/components/ui/Toast";
import { relativeDate, roleLabel, text } from "@/lib/format";

import { useCreateInvitation, useRevokeInvitation } from "./queries";

export function InvitationsPanel({ invitations, projects, canInvite }: { invitations: Invitation[]; projects: ProjectSummary[]; canInvite: boolean }) {
  const [open, setOpen] = useState(false); const [revokeTarget, setRevokeTarget] = useState<Invitation | null>(null); const revoke = useRevokeInvitation(); const { toast } = useToast();
  const confirmRevoke = async () => { if (!revokeTarget) return; try { await revoke.mutateAsync(revokeTarget.id); setRevokeTarget(null); toast({ title: "Invitación revocada", tone: "success" }); } catch (error) { toast({ title: "No se pudo revocar", description: (error as Error).message, tone: "danger" }); } };
  return <section><header className="section-heading"><span><h2>Invitaciones pendientes</h2><p>Enlaces de un solo uso para incorporar personas.</p></span><Button disabled={!canInvite} onClick={() => setOpen(true)}>Invitar usuario</Button></header>{invitations.length ? <div className="invitation-list">{invitations.map((invitation) => <article key={invitation.id}><span><strong>{text(invitation.email)}</strong><small>{roleLabel(invitation.organization_role)}{invitation.project_name ? ` · ${text(invitation.project_name)}` : ""}</small></span><StatusChip tone="warning">Vence {relativeDate(invitation.expires_at)}</StatusChip><Button size="sm" variant="danger" onClick={() => setRevokeTarget(invitation)}>Revocar</Button></article>)}</div> : <EmptyState title="No hay invitaciones pendientes" /> }<InvitationDialog open={open} onOpenChange={setOpen} projects={projects} /><ConfirmDialog open={Boolean(revokeTarget)} title="Revocar invitación" description={`Se invalidará la invitación para ${revokeTarget?.email || "esta persona"}.`} confirmLabel="Revocar" destructive busy={revoke.isPending} onConfirm={() => void confirmRevoke()} onOpenChange={(value) => { if (!value) setRevokeTarget(null); }} /></section>;
}

function InvitationDialog({ open, onOpenChange, projects }: { open: boolean; onOpenChange: (open: boolean) => void; projects: ProjectSummary[] }) {
  const [email, setEmail] = useState(""); const [organizationRole, setOrganizationRole] = useState("member"); const [projectID, setProjectID] = useState(""); const [projectRole, setProjectRole] = useState("viewer"); const [hours, setHours] = useState(24); const [link, setLink] = useState(""); const create = useCreateInvitation(); const { toast } = useToast();
  const submit = async (event: FormEvent) => { event.preventDefault(); try { const result = await create.mutateAsync({ email: email.trim(), organization_role: organizationRole, project_id: organizationRole === "member" ? projectID || undefined : undefined, project_role: organizationRole === "member" && projectID ? projectRole : undefined, expires_in_hours: hours }); const wrapper = result as { invitation?: Invitation; secret?: string }; const invitation = wrapper.invitation || result as Invitation; const value = wrapper.secret || invitation.secret; setLink(value ? `${window.location.origin}/admin/#invite=${encodeURIComponent(value)}` : ""); toast({ title: "Invitación creada", tone: "success" }); } catch (error) { toast({ title: "No se pudo crear", description: (error as Error).message, tone: "danger" }); } };
  const close = () => { onOpenChange(false); setEmail(""); setLink(""); };
  return <Dialog open={open} onOpenChange={(value) => value ? onOpenChange(true) : close()}><DialogContent><form onSubmit={submit}><DialogHeader><p className="pact-kicker">NUEVA PERSONA</p><DialogTitle>Invitar usuario</DialogTitle></DialogHeader><DialogBody className="pact-form-stack">{link ? <><p>Comparte este enlace de un solo uso:</p><div className="copy-field"><input readOnly value={link} /><Button variant="secondary" onClick={() => void navigator.clipboard.writeText(link)}>Copiar</Button></div></> : <><label className="pact-field"><span>Correo</span><input autoFocus type="email" required value={email} onChange={(event) => setEmail(event.target.value)} /></label><label className="pact-field"><span>Rol de organización</span><select value={organizationRole} onChange={(event) => setOrganizationRole(event.target.value)}><option value="member">Miembro</option><option value="admin">Administrador</option></select></label>{organizationRole === "member" ? <div className="pact-form-grid"><label className="pact-field"><span>Workspace inicial</span><select value={projectID} onChange={(event) => setProjectID(event.target.value)}><option value="">Sin workspace inicial</option>{projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label><label className="pact-field"><span>Rol del workspace</span><select disabled={!projectID} value={projectRole} onChange={(event) => setProjectRole(event.target.value)}><option value="viewer">Observador</option><option value="contributor">Colaborador</option><option value="maintainer">Responsable</option></select></label></div> : null}<label className="pact-field"><span>Validez</span><select value={hours} onChange={(event) => setHours(Number(event.target.value))}><option value={24}>24 horas</option><option value={72}>3 días</option><option value={168}>7 días</option></select></label></>}</DialogBody><DialogFooter><Button variant="secondary" onClick={close}>{link ? "Cerrar" : "Cancelar"}</Button>{!link ? <Button type="submit" loading={create.isPending}>Crear invitación</Button> : null}</DialogFooter></form></DialogContent></Dialog>;
}
